import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import type { TestPack, TestPackItem } from "@/lib/testpack/testpack-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function hasAny(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();

  return keywords.some((keyword) => lower.includes(keyword.toLowerCase()));
}

function resolveReadinessSignal(project: ProjectRuntimeArtifact) {
  const text = [
    project.input,
    sectionToText(project.prd),
    sectionToText(project.architecture),
    sectionToText(project.tasks),
    sectionToText(project.exportPack),
  ].join("\n");

  const hasSecurity = hasAny(text, [
    "auth",
    "authentication",
    "authorization",
    "rls",
    "security",
    "permission",
  ]);

  const hasDeploy = hasAny(text, [
    "deploy",
    "vercel",
    "production",
    "rollback",
    "environment",
  ]);

  const hasTasks = sectionToText(project.tasks).trim().length > 0;

  if (hasSecurity && hasDeploy && hasTasks) return "safe_to_test";
  if (hasTasks || hasSecurity || hasDeploy) return "needs_review";
  return "blocked";
}

function buildTestItems(): TestPackItem[] {
  return [
    {
      id: "smoke-build",
      category: "smoke",
      priority: "critical",
      title: "Production build must pass",
      command: "npm run build",
      expectedResult: "The project builds without TypeScript, route, or lint blocking errors.",
      failureRisk: "The project cannot be deployed safely if the production build fails.",
    },
    {
      id: "smoke-dev",
      category: "smoke",
      priority: "high",
      title: "Development server starts",
      command: "npm run dev",
      expectedResult: "The local development server starts and the app loads in the browser.",
      failureRisk: "Developers cannot verify the product manually if the dev server fails.",
    },
    {
      id: "route-dashboard",
      category: "routes",
      priority: "high",
      title: "Dashboard route works",
      expectedResult: "/dashboard loads without blank screen or navigation breakage.",
      failureRisk: "Users cannot return to the operating system home base.",
    },
    {
      id: "route-project",
      category: "routes",
      priority: "critical",
      title: "Project runtime route works",
      expectedResult: "/project/[id] loads Project Brain, PRD, Architecture, Tasks, and Export Pack.",
      failureRisk: "The core project runtime becomes unusable.",
    },
    {
      id: "route-router",
      category: "routes",
      priority: "high",
      title: "AI Router route works",
      expectedResult: "/project/[id]/router loads and local route execution works.",
      failureRisk: "AI routing workflow cannot be tested or audited.",
    },
    {
      id: "route-code",
      category: "routes",
      priority: "critical",
      title: "Code Pack route works",
      expectedResult: "/project/[id]/code loads generated files and ZIP export controls.",
      failureRisk: "Users cannot export generated implementation packages.",
    },
    {
      id: "route-readiness",
      category: "routes",
      priority: "high",
      title: "Readiness route works",
      expectedResult: "/project/[id]/readiness loads readiness score and gate details.",
      failureRisk: "Users cannot verify whether the project is safe to build or deploy.",
    },
    {
      id: "route-deploy",
      category: "routes",
      priority: "high",
      title: "Deploy route works",
      expectedResult: "/project/[id]/deploy loads environment, build, rollback, and launch checklist.",
      failureRisk: "Users may deploy without required operational checks.",
    },
    {
      id: "security-env",
      category: "security",
      priority: "critical",
      title: "No real secrets committed",
      command:
        "git ls-files | grep -E '(^|/)\\.env($|\\.|/)|\\.(pem|key|p12|pfx)$' | grep -v '\\.env\\.example$' || true",
      expectedResult: "No real .env, .env.local, PEM, key, p12, or pfx files are tracked.",
      failureRisk: "Private credentials could be leaked to GitHub.",
    },
    {
      id: "security-env-example",
      category: "security",
      priority: "critical",
      title: ".env.example is placeholder-only",
      command: "cat .env.example",
      expectedResult:
        "Only empty placeholder keys are shown. No real Supabase, OpenAI, Anthropic, Gemini, or service role key exists.",
      failureRisk: "A template file could accidentally expose production credentials.",
    },
    {
      id: "data-local-fallback",
      category: "data",
      priority: "high",
      title: "LocalStorage fallback works",
      expectedResult:
        "Projects remain usable when Supabase is unavailable or the user is not signed in.",
      failureRisk: "Beginner users lose generated projects or cannot continue offline/local-first.",
    },
    {
      id: "data-supabase-hybrid",
      category: "data",
      priority: "high",
      title: "Supabase hybrid storage works",
      expectedResult:
        "Signed-in users can save and reopen cloud-backed projects without losing local fallback.",
      failureRisk: "Cloud project sync becomes unreliable.",
    },
    {
      id: "deployment-node",
      category: "deployment",
      priority: "critical",
      title: "Node 20 runtime is pinned",
      command: "node -v && cat .nvmrc",
      expectedResult: "Node 20 is used locally and .nvmrc contains 20.",
      failureRisk: "Vercel or Codespaces may build with an incompatible Node version.",
    },
    {
      id: "acceptance-flow",
      category: "acceptance",
      priority: "critical",
      title: "Full product flow is usable",
      expectedResult:
        "User can generate a project, open Project Runtime, run AI Router, view Code Pack, run Tests, check Readiness, review Deploy Pack, and inspect Activity.",
      failureRisk: "The product feels like disconnected pages instead of an operating system.",
    },
  ];
}

function buildManualChecklist(): string[] {
  return [
    "Generate a fresh project from Dashboard.",
    "Open the generated project page.",
    "Confirm top navigation order: Project → AI Router → Code Pack → Tests → Readiness → Deploy → Activity.",
    "Run one AI Router local task.",
    "Open Code Pack and export ZIP.",
    "Open Tests and review all critical checks.",
    "Open Readiness and confirm the score renders.",
    "Open Deploy and review environment variable warnings.",
    "Open Activity and confirm relevant runtime events exist.",
    "Run npm run build before Git commit.",
  ];
}

function buildNextActions(signal: TestPack["readinessSignal"]): string[] {
  if (signal === "safe_to_test") {
    return [
      "Run npm run build.",
      "Verify all project runtime routes manually.",
      "Export ZIP and validate the generated package structure.",
      "Move to deployment event tracking after tests pass.",
    ];
  }

  if (signal === "needs_review") {
    return [
      "Review security, deployment, and task coverage before treating this project as production-ready.",
      "Run the Readiness Gate.",
      "Fix missing product, architecture, or deployment details.",
      "Repeat Test Pack checks after updates.",
    ];
  }

  return [
    "Do not deploy yet.",
    "Strengthen PRD, architecture, tasks, security, and deployment plan first.",
    "Generate Code Pack only after core planning artifacts are complete.",
    "Run tests again after the project has enough implementation detail.",
  ];
}

export function generateTestPack(project: ProjectRuntimeArtifact): TestPack {
  const readinessSignal = resolveReadinessSignal(project);

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    readinessSignal,
    items: buildTestItems(),
    manualChecklist: buildManualChecklist(),
    nextActions: buildNextActions(readinessSignal),
    generatedAt: new Date().toISOString(),
  };
}