import { generateAiRouterPlan } from "@/lib/ai-router/router-engine";
import { generateCodePack } from "@/lib/codegen/codegen-engine";
import { generateDeploymentPack } from "@/lib/deploy/deploy-engine";
import { generateProjectMonitorReport } from "@/lib/monitor/monitor-engine";
import { generateOpsRunbook } from "@/lib/ops/ops-engine";
import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import { generateReadinessReport } from "@/lib/readiness/readiness-engine";
import { generateTestPack } from "@/lib/testpack/testpack-engine";
import type {
  HandoverAsset,
  HandoverSection,
  ProjectHandoverPack,
} from "@/lib/handover/handover-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function getAssetStatus(score: number): HandoverAsset["status"] {
  if (score >= 75) return "ready";
  if (score >= 55) return "needs_review";
  return "missing";
}

function resolveHandoverStatus({
  readinessScore,
  monitorScore,
  deployRisk,
}: {
  readinessScore: number;
  monitorScore: number;
  deployRisk: "low" | "medium" | "high";
}): ProjectHandoverPack["handoverStatus"] {
  if (readinessScore >= 75 && monitorScore >= 75 && deployRisk !== "high") {
    return "ready_for_internal_handoff";
  }

  if (readinessScore >= 55 && monitorScore >= 55) {
    return "needs_review";
  }

  return "not_ready";
}

function buildAssets(project: ProjectRuntimeArtifact): HandoverAsset[] {
  const readinessReport = generateReadinessReport(project);
  const codePack = generateCodePack(project);
  const deploymentPack = generateDeploymentPack(project);
  const testPack = generateTestPack(project);
  const monitorReport = generateProjectMonitorReport(project);
  const opsRunbook = generateOpsRunbook(project);
  const routerPlan = generateAiRouterPlan(project);

  const projectText = [
    project.input,
    sectionToText(project.prd),
    sectionToText(project.architecture),
    sectionToText(project.tasks),
    sectionToText(project.exportPack),
  ].join("\n");

  const hasProjectRuntime = projectText.trim().length > 0;
  const testScore =
    testPack.readinessSignal === "safe_to_test"
      ? 86
      : testPack.readinessSignal === "needs_review"
        ? 66
        : 42;

  const deployScore =
    deploymentPack.riskLevel === "low"
      ? 86
      : deploymentPack.riskLevel === "medium"
        ? 66
        : 42;

  const opsScore =
    opsRunbook.operatingStage === "post_launch"
      ? 86
      : opsRunbook.operatingStage === "launch_ready"
        ? 72
        : 52;

  const routerScore =
    routerPlan.mode === "enterprise"
      ? 86
      : routerPlan.mode === "cloud_ready"
        ? 76
        : 68;

  return [
    {
      id: "project-runtime",
      name: "Project Runtime",
      type: "runtime",
      status: hasProjectRuntime ? "ready" : "missing",
      description:
        "Project Brain, PRD, Architecture, Tasks, and Export Pack are available in the main runtime.",
    },
    {
      id: "ai-router",
      name: "AI Router",
      type: "ai",
      status: getAssetStatus(routerScore),
      description:
        "Local-first AI routing rules and task runner are available for product, architecture, code, deploy, and monitor tasks.",
    },
    {
      id: "code-pack",
      name: "Code Pack",
      type: "code",
      status: codePack.fileCount >= 5 ? "ready" : "needs_review",
      description: `${codePack.fileCount} generated files are available for review and ZIP export.`,
    },
    {
      id: "tests",
      name: "Test Pack",
      type: "test",
      status: getAssetStatus(testScore),
      description:
        "Smoke, route, security, data, deployment, and acceptance checks are available.",
    },
    {
      id: "readiness",
      name: "Readiness Gate",
      type: "readiness",
      status: getAssetStatus(readinessReport.overallScore),
      description: `Readiness score is ${readinessReport.overallScore}/100.`,
    },
    {
      id: "deploy",
      name: "Deployment Pack",
      type: "deploy",
      status: getAssetStatus(deployScore),
      description: `Deployment risk is ${deploymentPack.riskLevel}.`,
    },
    {
      id: "monitor",
      name: "Project Monitor",
      type: "monitor",
      status: getAssetStatus(monitorReport.overallHealthScore),
      description: `Runtime health score is ${monitorReport.overallHealthScore}/100.`,
    },
    {
      id: "ops",
      name: "Operations Runbook",
      type: "ops",
      status: getAssetStatus(opsScore),
      description: `Operating stage is ${opsRunbook.operatingStage}.`,
    },
  ];
}

function buildSections(project: ProjectRuntimeArtifact): HandoverSection[] {
  return [
    {
      id: "product-context",
      title: "Product Context",
      priority: "critical",
      summary:
        "What the next owner must understand before changing the product.",
      items: [
        `Original request: ${project.input}`,
        "Review Project Brain, PRD, Architecture, Tasks, and Export Pack before development.",
        "Preserve the product flow and do not downgrade it into a prompt pack or static document.",
        "Keep beginner mode and professional developer mode in mind for future UI decisions.",
      ],
    },
    {
      id: "technical-context",
      title: "Technical Context",
      priority: "critical",
      summary:
        "Technical assumptions and stack rules that must be preserved.",
      items: [
        "Default stack: Next.js, TypeScript, Tailwind, Supabase, Vercel.",
        "Project routes must keep using app/project/[id]. Do not reintroduce [projectId].",
        "Keep LocalStorage fallback and Supabase hybrid storage.",
        "Do not break Dashboard, Project Runtime, Code Pack, Tests, Readiness, Deploy, Monitor, Ops, or Activity.",
      ],
    },
    {
      id: "security-context",
      title: "Security Context",
      priority: "critical",
      summary:
        "Secret handling and deployment safety rules for any future owner.",
      items: [
        "Never commit .env, .env.local, private keys, API keys, service role keys, tokens, or PEM files.",
        "Never use git add . for project commits.",
        "Before every commit, run tracked-secret checks.",
        "AI provider keys must be server-side only and never exposed through NEXT_PUBLIC variables.",
      ],
    },
    {
      id: "handover-checklist",
      title: "Handover Checklist",
      priority: "high",
      summary:
        "Minimum checklist before giving this project to another developer or team.",
      items: [
        "Run npm run build and confirm it passes.",
        "Open /project/[id] and confirm Action Hub loads.",
        "Open Code Pack and confirm ZIP export works.",
        "Open Tests, Readiness, Deploy, Monitor, Ops, and Activity.",
        "Confirm the latest runtime-alpha tag exists and Git working tree is clean.",
      ],
    },
    {
      id: "next-owner-tasks",
      title: "Next Owner Tasks",
      priority: "medium",
      summary:
        "What the next developer or operator should do after receiving the handover.",
      items: [
        "Review all generated artifacts before modifying code.",
        "Run local smoke tests and route checks.",
        "Review Supabase RLS and workspace ownership before production use.",
        "Add server-side provider routes before enabling real AI providers.",
        "Add real deployment integration only after deployment event tracking remains stable.",
      ],
    },
  ];
}

function buildRisks(
  handoverStatus: ProjectHandoverPack["handoverStatus"],
): string[] {
  if (handoverStatus === "ready_for_internal_handoff") {
    return [
      "This project is suitable for internal handoff, but production launch still requires final build, test, deploy, and smoke checks.",
      "External AI providers should not be enabled until server-side secret handling is added.",
    ];
  }

  if (handoverStatus === "needs_review") {
    return [
      "Some generated assets need review before handoff.",
      "The next owner should inspect Tests, Readiness, Deploy, Monitor, and Ops before implementation.",
      "Production deployment should wait until critical checks are cleared.",
    ];
  }

  return [
    "This project is not ready for handoff.",
    "Core planning, testing, readiness, monitoring, or deployment review is incomplete.",
    "Do not transfer ownership until missing or critical assets are resolved.",
  ];
}

function buildNextOwnerActions(
  handoverStatus: ProjectHandoverPack["handoverStatus"],
): string[] {
  if (handoverStatus === "ready_for_internal_handoff") {
    return [
      "Copy the handover pack Markdown.",
      "Give the next owner the repository, latest tag, deployment notes, and project ID.",
      "Ask the next owner to run npm run build before making changes.",
      "Use Ops Runbook for incidents and release control.",
    ];
  }

  if (handoverStatus === "needs_review") {
    return [
      "Review assets marked needs_review.",
      "Run Tests and Readiness again.",
      "Resolve monitor warnings before handoff.",
      "Update Ops Runbook if deployment or security assumptions changed.",
    ];
  }

  return [
    "Strengthen product, architecture, tasks, tests, readiness, deploy, monitor, and ops first.",
    "Do not hand over this project as production-ready.",
    "Generate a new handover pack after critical gaps are resolved.",
  ];
}

export function generateProjectHandoverPack(
  project: ProjectRuntimeArtifact,
): ProjectHandoverPack {
  const readinessReport = generateReadinessReport(project);
  const monitorReport = generateProjectMonitorReport(project);
  const deploymentPack = generateDeploymentPack(project);

  const handoverStatus = resolveHandoverStatus({
    readinessScore: readinessReport.overallScore,
    monitorScore: monitorReport.overallHealthScore,
    deployRisk: deploymentPack.riskLevel,
  });

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    handoverStatus,
    assets: buildAssets(project),
    sections: buildSections(project),
    risks: buildRisks(handoverStatus),
    nextOwnerActions: buildNextOwnerActions(handoverStatus),
    generatedAt: new Date().toISOString(),
  };
}
