import { Check, Building2, Briefcase, User, Users } from "lucide-react";
import { pricingPlans } from "@/data/pricing";
import { Container } from "@/components/ui/Container";
import { SectionTitle } from "@/components/ui/SectionTitle";
import { Button } from "@/components/ui/Button";
const icons = [User, Briefcase, Users, Building2];
export function Pricing() {
  return <section id="pricing" className="bg-white py-24 dark:bg-slate-950"><Container><SectionTitle eyebrow="Pricing" title="Start Small. Grow Into a Product Operating System." description="Begin with a simple workflow and expand into team, enterprise and implementation support." /><div className="grid gap-6 lg:grid-cols-4">{pricingPlans.map((p, i) => { const Icon = icons[i]; return <div key={p.name} className={`relative rounded-3xl border p-6 transition ${p.featured ? "scale-[1.02] border-brandBlue bg-white shadow-2xl ring-2 ring-brandBlue dark:bg-white/[0.06]" : "border-slate-200 bg-white shadow-sm hover:shadow-md dark:border-white/10 dark:bg-white/[0.03]"}`}>{p.badge && <div className={`absolute right-5 top-5 rounded-full px-3 py-1 text-xs font-semibold ${p.featured ? "bg-brandBlue text-white" : "bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300"}`}>{p.badge}</div>}<div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-brandBlue dark:bg-brandCyan/10 dark:text-brandCyan"><Icon size={26} /></div><h3 className="mt-6 text-xl font-bold text-primary dark:text-white">{p.name}</h3><p className="mt-3 min-h-[48px] text-sm leading-6 text-mutedText dark:text-slate-400">{p.description}</p><div className="mt-6"><p className="text-3xl font-bold text-primary dark:text-white">{p.price}</p></div><ul className="mt-6 space-y-4">{p.features.map((f) => <li key={f} className="flex gap-3 text-sm leading-6 text-slate-600 dark:text-slate-300"><Check className="mt-1 shrink-0 text-brandCyan" size={18} /><span>{f}</span></li>)}</ul><div className="mt-8"><Button href="#contact" variant={p.featured ? "primary" : "secondary"}>{p.cta}</Button></div></div>; })}</div></Container></section>;
}
