import { generateAiRouterPlan } from "@/lib/ai-router/router-engine";
import { generateCodePack } from "@/lib/codegen/codegen-engine";
import { generateDeploymentPack } from "@/lib/deploy/deploy-engine";
import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import { generateReadinessReport } from "@/lib/readiness/readiness-engine";
import { generateTestPack } from "@/lib/testpack/testpack-engine";
import type {
  MonitorIncident,
  MonitorRiskLevel,
  MonitorSignal,
  MonitorSignalStatus,
  ProjectMonitorReport,
} from "@/lib/monitor/monitor-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function toStatus(score: number): MonitorSignalStatus {
  if (score >= 80) return "healthy";
  if (score >= 60) return "warning";
  return "critical";
}

function toRiskLevel(score: number): MonitorRiskLevel {
  if (score >= 80) return "low";
  if (score >= 60) return "medium";
  return "high";
}

function buildIncidents(signals: MonitorSignal[]): MonitorIncident[] {
  return signals
    .filter((signal) => signal.status !== "healthy")
    .map((signal) => ({
      id: `incident-${signal.id}`,
      title: `${signal.title} needs attention`,
      severity: signal.status,
      detail: signal.description,
      recommendedFix: signal.nextAction,
    }));
}

function averageScore(signals: MonitorSignal[]): number {
  if (signals.length === 0) return 0;

  const total = signals.reduce((sum, signal) => sum + signal.score, 0);

  return Math.round(total / signals.length);
}

export function generateProjectMonitorReport(
  project: ProjectRuntimeArtifact,
): ProjectMonitorReport {
  const readinessReport = generateReadinessReport(project);
  const deploymentPack = generateDeploymentPack(project);
  const testPack = generateTestPack(project);
  const codePack = generateCodePack(project);
  const routerPlan = generateAiRouterPlan(project);

  const projectText = [
    project.input,
    sectionToText(project.prd),
    sectionToText(project.architecture),
    sectionToText(project.tasks),
    sectionToText(project.exportPack),
  ].join("\n");

  const hasAuditSignals =
    projectText.toLowerCase().includes("audit") ||
    projectText.toLowerCase().includes("activity") ||
    projectText.toLowerCase().includes("monitor");

  const testScore =
    testPack.readinessSignal === "safe_to_test"
      ? 88
      : testPack.readinessSignal === "needs_review"
        ? 68
        : 42;

  const deployScore =
    deploymentPack.riskLevel === "low"
      ? 88
      : deploymentPack.riskLevel === "medium"
        ? 66
        : 45;

  const routerScore =
    routerPlan.mode === "enterprise"
      ? 86
      : routerPlan.mode === "cloud_ready"
        ? 76
        : 70;

  const monitorScore = hasAuditSignals ? 82 : 58;

  const signals: MonitorSignal[] = [
    {
      id: "readiness",
      title: "Readiness Gate",
      status: toStatus(readinessReport.overallScore),
      score: readinessReport.overallScore,
      description:
        "Tracks whether product, architecture, security, delivery, and operations are ready.",
      nextAction: "Open Readiness and resolve all critical blocking items.",
    },
    {
      id: "tests",
      title: "Test Pack",
      status: toStatus(testScore),
      score: testScore,
      description:
        "Tracks smoke tests, route tests, security checks, data checks, deployment preflight, and acceptance flow.",
      nextAction: "Open Tests and complete all critical QA checks before deployment.",
    },
    {
      id: "code",
      title: "Code Pack",
      status: toStatus(codePack.fileCount >= 5 ? 82 : 56),
      score: codePack.fileCount >= 5 ? 82 : 56,
      description:
        "Tracks whether the project has enough generated starter files to review and export.",
      nextAction: "Open Code Pack, review generated files, and export ZIP for validation.",
    },
    {
      id: "deploy",
      title: "Deployment Pack",
      status: toStatus(deployScore),
      score: deployScore,
      description:
        "Tracks deployment risk, environment variables, build commands, and rollback readiness.",
      nextAction: "Open Deploy and verify preflight, env vars, rollback, and event tracking.",
    },
    {
      id: "router",
      title: "AI Router",
      status: toStatus(routerScore),
      score: routerScore,
      description:
        "Tracks whether AI routing is local-first, secret-safe, and ready for future provider execution.",
      nextAction: "Open AI Router and run at least one local route task.",
    },
    {
      id: "monitoring",
      title: "Monitoring Coverage",
      status: toStatus(monitorScore),
      score: monitorScore,
      description:
        "Tracks whether Activity Audit, runtime events, AI route events, and deployment events are visible.",
      nextAction: "Open Activity and confirm runtime, AI, workspace, and deployment events are recorded.",
    },
  ];

  const overallHealthScore = averageScore(signals);
  const status = toStatus(overallHealthScore);
  const riskLevel = toRiskLevel(overallHealthScore);
  const incidents = buildIncidents(signals);

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    overallHealthScore,
    status,
    riskLevel,
    signals,
    incidents,
    nextActions:
      status === "healthy"
        ? [
            "Continue monitoring Activity after deployment events.",
            "Run smoke tests after every deployment.",
            "Keep rollback tags before production changes.",
          ]
        : [
            "Fix warning and critical monitor signals before production launch.",
            "Run Tests, Readiness, Deploy, and Activity checks in order.",
            "Do not treat the project as production-ready until critical incidents are cleared.",
          ],
    generatedAt: new Date().toISOString(),
  };
}