import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import type {
  DeployChecklistItem,
  DeployCommand,
  DeploymentPack,
  DeployEnvironmentVariable,
  DeployRiskLevel,
} from "@/lib/deploy/deploy-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function hasAny(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();

  return keywords.some((keyword) => lower.includes(keyword.toLowerCase()));
}

function resolveRiskLevel(project: ProjectRuntimeArtifact): DeployRiskLevel {
  const architectureText = sectionToText(project.architecture);
  const tasksText = sectionToText(project.tasks);
  const exportText = sectionToText(project.exportPack);

  const allText = [
    project.input,
    architectureText,
    tasksText,
    exportText,
  ].join("\n");

  const hasSecurity = hasAny(allText, [
    "auth",
    "authentication",
    "authorization",
    "rls",
    "permission",
    "role",
    "access control",
  ]);

  const hasDeployment = hasAny(allText, [
    "deploy",
    "deployment",
    "vercel",
    "production",
    "rollback",
    "environment",
  ]);

  const hasMonitoring = hasAny(allText, [
    "monitor",
    "logging",
    "audit",
    "alert",
    "health",
  ]);

  if (hasSecurity && hasDeployment && hasMonitoring) return "low";
  if (hasSecurity || hasDeployment) return "medium";
  return "high";
}

function getRiskSummary(riskLevel: DeployRiskLevel): string {
  if (riskLevel === "low") {
    return "The project has clear deployment, security, and monitoring signals. It is suitable for controlled staging deployment after final manual review.";
  }

  if (riskLevel === "medium") {
    return "The project has partial deployment readiness. Review environment variables, authentication, database ownership, and rollback before production.";
  }

  return "The project should not be deployed to production yet. Security, environment handling, monitoring, and rollback planning need stronger coverage.";
}

function buildEnvironmentVariables(): DeployEnvironmentVariable[] {
  return [
    {
      key: "NEXT_PUBLIC_SUPABASE_URL",
      required: true,
      visibility: "public",
      description: "Public Supabase project URL used by the browser client.",
    },
    {
      key: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
      required: true,
      visibility: "public",
      description: "Public Supabase anon key protected by RLS policies.",
    },
    {
      key: "SUPABASE_SERVICE_ROLE_KEY",
      required: false,
      visibility: "server",
      description:
        "Server-only service role key. Never expose in browser code and never commit to Git.",
    },
  ];
}

function buildCommands(): DeployCommand[] {
  return [
    {
      label: "Install dependencies",
      command: "npm install",
      description: "Install all project dependencies before local build.",
    },
    {
      label: "Run production build",
      command: "npm run build",
      description: "Validate TypeScript, routes, and production build output.",
    },
    {
      label: "Run development server",
      command: "npm run dev",
      description: "Start local development server for smoke testing.",
    },
    {
      label: "Deploy to Vercel",
      command: "git push",
      description:
        "Push to GitHub. Vercel will deploy automatically when the repository is connected.",
    },
  ];
}

function buildChecklist(riskLevel: DeployRiskLevel): DeployChecklistItem[] {
  return [
    {
      id: "node-version",
      title: "Node.js 20 is pinned",
      detail:
        "Confirm .nvmrc and package.json engines require Node 20+ before deploying.",
      required: true,
    },
    {
      id: "build-pass",
      title: "Production build passes",
      detail: "Run npm run build and fix all TypeScript or route errors.",
      required: true,
    },
    {
      id: "env-safe",
      title: "Environment variables are configured safely",
      detail:
        "Only NEXT_PUBLIC_* variables go to the browser. Private keys must stay server-side.",
      required: true,
    },
    {
      id: "supabase-rls",
      title: "Supabase RLS is enabled",
      detail:
        "Verify all user-owned, workspace-owned, project-owned tables have RLS policies.",
      required: true,
    },
    {
      id: "audit-monitoring",
      title: "Audit and activity logs are enabled",
      detail:
        "Confirm key runtime events are written to audit_events and visible in /activity.",
      required: riskLevel !== "low",
    },
    {
      id: "rollback-ready",
      title: "Rollback path is ready",
      detail:
        "Confirm Git tags and Vercel previous deployments can be restored if production fails.",
      required: true,
    },
  ];
}

function buildRollbackPlan(): string[] {
  return [
    "Keep the latest stable Git tag before production deployment.",
    "If deployment fails, rollback to the previous successful Vercel deployment.",
    "If database migration fails, stop deployment and restore from the last known stable schema.",
    "Never roll forward with broken RLS, missing environment variables, or failed build output.",
    "Document the failed deployment reason in Activity / Audit logs.",
  ];
}

function buildNextActions(riskLevel: DeployRiskLevel): string[] {
  if (riskLevel === "low") {
    return [
      "Run npm run build one final time.",
      "Confirm Vercel environment variables.",
      "Deploy to staging or preview environment.",
      "Run smoke tests on /dashboard, /workspace, /activity, /project/[id], /code, and /readiness.",
    ];
  }

  if (riskLevel === "medium") {
    return [
      "Review authentication and RLS policies before production.",
      "Confirm all required environment variables exist in Vercel.",
      "Run smoke tests on all runtime pages.",
      "Prepare rollback tag before deploying.",
    ];
  }

  return [
    "Do not deploy to production yet.",
    "Improve security, database ownership, monitoring, and rollback plans.",
    "Run the Production Readiness Gate again.",
    "Only deploy after build, auth, RLS, and environment checks pass.",
  ];
}

export function generateDeploymentPack(
  project: ProjectRuntimeArtifact,
): DeploymentPack {
  const riskLevel = resolveRiskLevel(project);

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    platform: "vercel",
    riskLevel,
    riskSummary: getRiskSummary(riskLevel),
    environmentVariables: buildEnvironmentVariables(),
    commands: buildCommands(),
    checklist: buildChecklist(riskLevel),
    rollbackPlan: buildRollbackPlan(),
    nextActions: buildNextActions(riskLevel),
    generatedAt: new Date().toISOString(),
  };
}