import type {
  AiCodeGenerationProvider,
  AiCodeGenerationRequest,
  AiCodeGenerationResponse,
  AiGeneratedCodeFile,
} from "./codegen-api-types";

type OpenAiMessage = {
  role: "system" | "user";
  content: string;
};

type OpenAiChoice = {
  message?: {
    content?: string;
  };
};

type OpenAiResponse = {
  choices?: OpenAiChoice[];
};

type ParsedProviderOutput = {
  summary: string;
  runInstructions: string[];
  files: AiGeneratedCodeFile[];
};

const MAX_PROMPT_LENGTH = 4000;
const DEFAULT_MAX_FILES = 8;

function cleanText(value: string, maxLength = MAX_PROMPT_LENGTH): string {
  return value.replace(/\u0000/g, "").trim().slice(0, maxLength);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function isSafeRelativePath(path: string): boolean {
  if (!path || path.startsWith("/") || path.includes("..") || path.includes("\\")) {
    return false;
  }

  return /^[a-zA-Z0-9._/@-]+$/.test(path);
}

function normalizeFile(value: unknown): AiGeneratedCodeFile | null {
  if (!isRecord(value)) {
    return null;
  }

  const path = asString(value.path);
  const language = asString(value.language) || "text";
  const purpose = asString(value.purpose) || "Generated project file";
  const content = asString(value.content);

  if (!isSafeRelativePath(path) || content.length === 0) {
    return null;
  }

  return {
    path,
    language,
    purpose,
    riskLevel: "review",
    content,
  };
}

function generateLocalFallback(prompt: string): ParsedProviderOutput {
  const safePrompt = cleanText(prompt, 1200);
  const productName = safePrompt
    .split(/\s+/)
    .slice(0, 4)
    .join(" ")
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .trim() || "DevCommander Generated App";

  const files: AiGeneratedCodeFile[] = [
    {
      path: "package.json",
      language: "json",
      purpose: "Project dependencies and scripts",
      riskLevel: "safe",
      content: JSON.stringify(
        {
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            next: "latest",
            react: "latest",
            "react-dom": "latest",
            typescript: "latest",
          },
          devDependencies: {},
        },
        null,
        2,
      ),
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      purpose: "Starter landing page generated from user prompt",
      riskLevel: "safe",
      content: `export default function HomePage() {
  return (
    <main className="min-h-screen bg-zinc-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-4xl">
        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-zinc-500">
          Generated by DevCommander OS
        </p>

        <h1 className="mt-6 text-4xl font-semibold tracking-tight sm:text-6xl">
          ${productName}
        </h1>

        <p className="mt-6 text-lg leading-8 text-zinc-400">
          ${safePrompt.replace(/`/g, "'")}
        </p>

        <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-6">
          <h2 className="text-xl font-semibold">Next step</h2>
          <p className="mt-3 text-zinc-400">
            Replace this starter page with real product screens, database logic,
            authentication, and deployment configuration.
          </p>
        </div>
      </section>
    </main>
  );
}
`,
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      purpose: "Root layout",
      riskLevel: "safe",
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${productName}",
  description: "Generated by DevCommander OS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
    {
      path: "app/globals.css",
      language: "css",
      purpose: "Minimal global styles",
      riskLevel: "safe",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

body {
  margin: 0;
}
`,
    },
    {
      path: ".env.example",
      language: "dotenv",
      purpose: "Safe empty environment template",
      riskLevel: "safe",
      content: `NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
`,
    },
    {
      path: "README.md",
      language: "md",
      purpose: "Run instructions",
      riskLevel: "safe",
      content: `# ${productName}

Generated by DevCommander OS.

## User prompt

${safePrompt}

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Security note

Do not commit real API keys. Keep private provider keys server-side only.
`,
    },
  ];

  return {
    summary: "Generated a safe local fallback Next.js starter code package.",
    runInstructions: ["npm install", "npm run dev", "npm run build"],
    files,
  };
}

function extractJson(text: string): string {
  const trimmed = text.trim();

  if (trimmed.startsWith("```")) {
    return trimmed
      .replace(/^```json/i, "")
      .replace(/^```/i, "")
      .replace(/```$/i, "")
      .trim();
  }

  return trimmed;
}

function parseProviderOutput(rawText: string, maxFiles: number): ParsedProviderOutput | null {
  try {
    const parsed = JSON.parse(extractJson(rawText)) as unknown;

    if (!isRecord(parsed)) {
      return null;
    }

    const rawFiles = Array.isArray(parsed.files) ? parsed.files : [];
    const files = rawFiles
      .map(normalizeFile)
      .filter((file): file is AiGeneratedCodeFile => file !== null)
      .slice(0, maxFiles);

    if (files.length === 0) {
      return null;
    }

    const rawInstructions = Array.isArray(parsed.runInstructions)
      ? parsed.runInstructions
      : [];

    return {
      summary: asString(parsed.summary) || "Generated code package from AI provider.",
      runInstructions: rawInstructions
        .map(asString)
        .filter((item) => item.length > 0)
        .slice(0, 8),
      files,
    };
  } catch {
    return null;
  }
}

async function generateWithOpenAi(
  prompt: string,
  maxFiles: number,
): Promise<ParsedProviderOutput | null> {
  const apiKey = process.env.OPENAI_API_KEY?.trim();

  if (!apiKey) {
    return null;
  }

  const model = process.env.OPENAI_MODEL?.trim() || "gpt-4o-mini";

  const messages: OpenAiMessage[] = [
    {
      role: "system",
      content:
        "You generate safe starter code packages. Return JSON only. Do not include secrets. Use relative file paths only. Do not use absolute paths. Do not include API keys.",
    },
    {
      role: "user",
      content: `Generate a Next.js TypeScript starter code package for this request:

${cleanText(prompt)}

Return exactly this JSON shape:
{
  "summary": "short summary",
  "runInstructions": ["npm install", "npm run dev", "npm run build"],
  "files": [
    {
      "path": "relative/path",
      "language": "tsx",
      "purpose": "why this file exists",
      "content": "file content"
    }
  ]
}

Limit to ${maxFiles} files.`,
    },
  ];

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30000);

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        temperature: 0.2,
        response_format: { type: "json_object" },
        messages,
      }),
    });

    if (!response.ok) {
      return null;
    }

    const data = (await response.json()) as OpenAiResponse;
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      return null;
    }

    return parseProviderOutput(content, maxFiles);
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

export async function generateCodeFromRequest(
  request: AiCodeGenerationRequest,
): Promise<AiCodeGenerationResponse> {
  const prompt = cleanText(request.prompt);
  const requestedProvider = request.provider || "local";
  const maxFiles = Math.max(
    1,
    Math.min(request.maxFiles || DEFAULT_MAX_FILES, 12),
  );

  if (prompt.length < 8) {
    throw new Error("Prompt is too short. Describe the product or problem first.");
  }

  let provider: AiCodeGenerationProvider = "local";
  let fallbackUsed = false;
  let generated: ParsedProviderOutput | null = null;

  if (requestedProvider === "openai") {
    generated = await generateWithOpenAi(prompt, maxFiles);

    if (generated) {
      provider = "openai";
    } else {
      fallbackUsed = true;
      generated = generateLocalFallback(prompt);
    }
  } else {
    generated = generateLocalFallback(prompt);
  }

  return {
    generatedAt: new Date().toISOString(),
    provider,
    fallbackUsed,
    summary: generated.summary,
    runInstructions: generated.runInstructions,
    files: generated.files.slice(0, maxFiles),
    safety: {
      secretsReturned: false,
      requiresHumanReview: true,
      warnings: [
        "Generated code must be reviewed before deployment.",
        "Do not commit real API keys.",
        "Run npm install and npm run build before launch.",
      ],
    },
  };
}
