import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import type { CodePack, CodePackFile } from "@/lib/codegen/codegen-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function cleanLine(value: string): string {
  return value
    .replace(/^[-*•\d.)\s]+/, "")
    .replace(/\*\*/g, "")
    .trim();
}

function extractListCandidates(text: string, limit: number): string[] {
  const candidates = text
    .split("\n")
    .map(cleanLine)
    .filter((line) => line.length >= 10 && line.length <= 120)
    .filter((line) => !line.includes("{") && !line.includes("}"))
    .filter((line) => !line.toLowerCase().startsWith("import "))
    .filter((line) => !line.toLowerCase().startsWith("export "));

  return Array.from(new Set(candidates)).slice(0, limit);
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function createPackageName(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);

  return slug || "generated-product";
}

function detectTechnicalStack(text: string): string[] {
  const lower = text.toLowerCase();
  const stack: string[] = [];

  if (lower.includes("next")) stack.push("Next.js");
  if (lower.includes("typescript")) stack.push("TypeScript");
  if (lower.includes("tailwind")) stack.push("Tailwind CSS");
  if (lower.includes("supabase")) stack.push("Supabase");
  if (lower.includes("postgres")) stack.push("Postgres");
  if (lower.includes("auth")) stack.push("Authentication");
  if (lower.includes("vercel")) stack.push("Vercel");

  if (stack.length === 0) {
    return ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Vercel"];
  }

  return Array.from(new Set(stack)).slice(0, 8);
}

function createReadme({
  title,
  summary,
  features,
  stack,
}: {
  title: string;
  summary: string;
  features: string[];
  stack: string[];
}): string {
  return [
    `# ${title}`,
    "",
    summary,
    "",
    "## Core Features",
    "",
    ...features.map((feature) => `- ${feature}`),
    "",
    "## Technical Stack",
    "",
    ...stack.map((item) => `- ${item}`),
    "",
    "## Getting Started",
    "",
    "```bash",
    "npm install",
    "npm run dev",
    "```",
    "",
    "## Environment Variables",
    "",
    "Copy `.env.example` to `.env.local` and fill in safe public keys only.",
    "",
    "```bash",
    "cp .env.example .env.local",
    "```",
    "",
    "## Security Notes",
    "",
    "- Never commit `.env`, `.env.local`, private keys, service role keys, or API secrets.",
    "- Keep Supabase service role keys server-side only.",
    "- Use RLS policies for user-owned and workspace-owned data.",
    "",
    "## Generated By",
    "",
    "DevCommander OS Code Pack Generator.",
    "",
  ].join("\n");
}

function createPackageJson(packageName: string): string {
  return JSON.stringify(
    {
      name: packageName,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        "@supabase/supabase-js": "latest",
        next: "latest",
        react: "latest",
        "react-dom": "latest",
      },
      devDependencies: {
        "@types/node": "latest",
        "@types/react": "latest",
        "@types/react-dom": "latest",
        autoprefixer: "latest",
        postcss: "latest",
        tailwindcss: "latest",
        typescript: "latest",
      },
      engines: {
        node: ">=20.0.0",
      },
    },
    null,
    2,
  );
}

function createProjectConfig({
  title,
  summary,
  features,
  stack,
}: {
  title: string;
  summary: string;
  features: string[];
  stack: string[];
}): string {
  const config = {
    title,
    summary,
    features,
    technicalStack: stack,
    readiness: "Generated starter. Review security, database, API routes, and deployment before production.",
  };

  return [
    "export const projectConfig = ",
    JSON.stringify(config, null, 2),
    " as const;",
    "",
  ].join("");
}

function createLayout(title: string, summary: string): string {
  return [
    'import type { ReactNode } from "react";',
    'import "./globals.css";',
    "",
    "export const metadata = {",
    `  title: ${JSON.stringify(title)},`,
    `  description: ${JSON.stringify(summary.slice(0, 150))},`,
    "};",
    "",
    "export default function RootLayout({",
    "  children,",
    "}: Readonly<{",
    "  children: ReactNode;",
    "}>) {",
    "  return (",
    '    <html lang="en">',
    '      <body>{children}</body>',
    "    </html>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function createPage(): string {
  return [
    'import GeneratedProductHero from "@/components/GeneratedProductHero";',
    'import { projectConfig } from "@/lib/project-config";',
    "",
    "export default function HomePage() {",
    "  return (",
    '    <main className="min-h-screen bg-zinc-950 px-6 py-10 text-white">',
    '      <div className="mx-auto max-w-6xl">',
    "        <GeneratedProductHero config={projectConfig} />",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function createHeroComponent(): string {
  return [
    "type HeroConfig = {",
    "  title: string;",
    "  summary: string;",
    "  features: readonly string[];",
    "  technicalStack: readonly string[];",
    "  readiness: string;",
    "};",
    "",
    "export default function GeneratedProductHero({",
    "  config,",
    "}: {",
    "  config: HeroConfig;",
    "}) {",
    "  return (",
    '    <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-8 shadow-2xl shadow-black/30">',
    '      <p className="text-sm font-semibold uppercase tracking-[0.3em] text-zinc-500">',
    "        Generated Product",
    "      </p>",
    "",
    '      <h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-tight sm:text-6xl">',
    "        {config.title}",
    "      </h1>",
    "",
    '      <p className="mt-6 max-w-3xl text-base leading-8 text-zinc-400">',
    "        {config.summary}",
    "      </p>",
    "",
    '      <div className="mt-8 grid gap-6 lg:grid-cols-2">',
    '        <div className="rounded-2xl border border-white/10 bg-black/20 p-5">',
    '          <h2 className="text-lg font-semibold">Core Features</h2>',
    '          <ul className="mt-4 grid gap-3 text-sm leading-6 text-zinc-300">',
    "            {config.features.map((feature) => (",
    '              <li key={feature} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3">',
    "                {feature}",
    "              </li>",
    "            ))}",
    "          </ul>",
    "        </div>",
    "",
    '        <div className="rounded-2xl border border-white/10 bg-black/20 p-5">',
    '          <h2 className="text-lg font-semibold">Technical Stack</h2>',
    '          <div className="mt-4 flex flex-wrap gap-2">',
    "            {config.technicalStack.map((item) => (",
    '              <span key={item} className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-zinc-950">',
    "                {item}",
    "              </span>",
    "            ))}",
    "          </div>",
    "",
    '          <p className="mt-5 rounded-2xl border border-amber-400/20 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100">',
    "            {config.readiness}",
    "          </p>",
    "        </div>",
    "      </div>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function createGlobalsCss(): string {
  return [
    "@tailwind base;",
    "@tailwind components;",
    "@tailwind utilities;",
    "",
    ":root {",
    "  color-scheme: dark;",
    "}",
    "",
    "body {",
    "  margin: 0;",
    "  background: #09090b;",
    "}",
    "",
    "* {",
    "  box-sizing: border-box;",
    "}",
    "",
  ].join("\n");
}

function createEnvExample(): string {
  return [
    "NEXT_PUBLIC_SUPABASE_URL=",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=",
    "",
  ].join("\n");
}

function createSchemaSql(title: string): string {
  return [
    "-- Generated starter schema. Review before production.",
    "create extension if not exists pgcrypto;",
    "",
    "create table if not exists public.projects (",
    "  id uuid primary key default gen_random_uuid(),",
    "  user_id uuid references auth.users(id) on delete cascade,",
    "  title text not null,",
    "  status text not null default 'active',",
    "  created_at timestamptz not null default now(),",
    "  updated_at timestamptz not null default now()",
    ");",
    "",
    "alter table public.projects enable row level security;",
    "",
    "create policy \"projects_select_own\"",
    "on public.projects",
    "for select",
    "to authenticated",
    "using (auth.uid() = user_id);",
    "",
    "create policy \"projects_insert_own\"",
    "on public.projects",
    "for insert",
    "to authenticated",
    "with check (auth.uid() = user_id);",
    "",
    `-- Seed idea: ${title}`,
    "",
  ].join("\n");
}

function createSmokeTest(title: string): string {
  return [
    `# Smoke Test Plan — ${title}`,
    "",
    "## Local Build",
    "",
    "- Run `npm install`.",
    "- Run `npm run build`.",
    "- Run `npm run dev`.",
    "",
    "## Manual QA",
    "",
    "- Home page loads without runtime errors.",
    "- Main CTA and feature sections render.",
    "- Environment variables are not committed.",
    "- Supabase RLS policies are enabled before production use.",
    "",
    "## Production Gate",
    "",
    "- Review authentication.",
    "- Review database ownership.",
    "- Review error handling.",
    "- Review deployment variables.",
    "- Review monitoring and audit logs.",
    "",
  ].join("\n");
}

export function generateCodePack(project: ProjectRuntimeArtifact): CodePack {
  const title = getProjectTitle(project);
  const summary = getProjectSummary(project);

  const prdText = sectionToText(project.prd);
  const architectureText = sectionToText(project.architecture);
  const tasksText = sectionToText(project.tasks);
  const exportText = sectionToText(project.exportPack);

  const allText = [
    project.input,
    prdText,
    architectureText,
    tasksText,
    exportText,
  ].join("\n");

  const extractedFeatures = extractListCandidates(`${prdText}\n${tasksText}`, 6);
  const features =
    extractedFeatures.length >= 3
      ? extractedFeatures
      : [
          "Generate a usable product runtime from one clear idea.",
          "Provide structured product, architecture, and task planning.",
          "Support secure authentication and project ownership.",
          "Prepare deployment and production readiness workflows.",
        ];

  const stack = detectTechnicalStack(allText);
  const packageName = createPackageName(title);

  const files: CodePackFile[] = [
    {
      path: "README.md",
      language: "markdown",
      description: "Project overview and setup instructions.",
      content: createReadme({
        title,
        summary,
        features,
        stack,
      }),
    },
    {
      path: "package.json",
      language: "json",
      description: "Starter dependencies and scripts.",
      content: createPackageJson(packageName),
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      description: "Next.js root layout.",
      content: createLayout(title, summary),
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      description: "Generated landing page entry.",
      content: createPage(),
    },
    {
      path: "app/globals.css",
      language: "css",
      description: "Tailwind base styles.",
      content: createGlobalsCss(),
    },
    {
      path: "components/GeneratedProductHero.tsx",
      language: "tsx",
      description: "Reusable generated product hero component.",
      content: createHeroComponent(),
    },
    {
      path: "lib/project-config.ts",
      language: "ts",
      description: "Generated project configuration.",
      content: createProjectConfig({
        title,
        summary,
        features,
        stack,
      }),
    },
    {
      path: ".env.example",
      language: "env",
      description: "Safe public environment variable template.",
      content: createEnvExample(),
    },
    {
      path: "supabase/schema.sql",
      language: "sql",
      description: "Starter Supabase schema with RLS.",
      content: createSchemaSql(title),
    },
    {
      path: "tests/smoke-test.md",
      language: "markdown",
      description: "Manual smoke test checklist.",
      content: createSmokeTest(title),
    },
  ];

  return {
    projectId: project.projectId,
    title,
    summary,
    fileCount: files.length,
    generatedAt: new Date().toISOString(),
    files,
    nextSteps: [
      "Review generated files before production use.",
      "Create the generated file tree in a new repository or export workflow.",
      "Add real API routes, database migrations, and authentication flows.",
      "Run npm install and npm run build in the generated project.",
      "Perform security review before deployment.",
    ],
  };
}