import { generateProjectMonitorReport } from "@/lib/monitor/monitor-engine";
import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";
import type { OpsRunbook, OpsRunbookSection } from "@/lib/ops/ops-types";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function resolveOperatingStage(score: number): OpsRunbook["operatingStage"] {
  if (score >= 85) return "post_launch";
  if (score >= 70) return "launch_ready";
  return "pre_launch";
}

function buildSections(project: ProjectRuntimeArtifact): OpsRunbookSection[] {
  const projectText = [
    project.input,
    sectionToText(project.prd),
    sectionToText(project.architecture),
    sectionToText(project.tasks),
    sectionToText(project.exportPack),
  ].join("\n");

  const hasAuth = /auth|login|permission|role|rls|security/i.test(projectText);
  const hasDeploy = /deploy|vercel|production|rollback|environment/i.test(
    projectText,
  );

  return [
    {
      id: "launch-control",
      title: "Launch Control",
      priority: "critical",
      summary:
        "Rules that must be checked before any production launch or public demo.",
      checklist: [
        "Run npm run build and confirm it passes.",
        "Open Tests and complete all critical checks.",
        "Open Readiness and confirm no critical blocker remains.",
        "Open Deploy and review environment variables, rollback, and deployment events.",
        "Confirm no .env, .env.local, private key, service role key, token, or PEM file is committed.",
      ],
    },
    {
      id: "incident-response",
      title: "Incident Response",
      priority: "critical",
      summary:
        "Standard response when production, routing, auth, deploy, or runtime errors happen.",
      checklist: [
        "Record the issue in Activity or deployment event tracking.",
        "Check the last Git commit and latest runtime-alpha tag.",
        "Inspect recent deployment events and AI route execution events.",
        "If deployment is broken, rollback to the last stable Vercel deployment or Git tag.",
        "Do not push emergency changes before running build and secret-safety checks.",
      ],
    },
    {
      id: "security-ops",
      title: "Security Operations",
      priority: hasAuth ? "critical" : "high",
      summary:
        "Security rules for auth, Supabase, RLS, secrets, API keys, and future AI providers.",
      checklist: [
        "Keep Supabase anon key public only when protected by RLS.",
        "Never expose service role keys or AI provider keys in browser code.",
        "Never use NEXT_PUBLIC_* for private provider credentials.",
        "Before Git commit, check tracked secrets with git ls-files.",
        "Review auth, workspace ownership, and project ownership before launch.",
      ],
    },
    {
      id: "data-ops",
      title: "Data & Storage Operations",
      priority: "high",
      summary:
        "Operational rules for LocalStorage fallback, Supabase hybrid storage, and project recovery.",
      checklist: [
        "Confirm local project fallback still works when signed out.",
        "Confirm signed-in users can reopen cloud-backed projects.",
        "Avoid destructive database migrations without rollback notes.",
        "Keep migration files ordered and documented.",
        "Do not delete existing project runtime fields without migration strategy.",
      ],
    },
    {
      id: "release-ops",
      title: "Release Operations",
      priority: hasDeploy ? "high" : "medium",
      summary:
        "Release workflow for tags, commits, deployment preflight, and rollback readiness.",
      checklist: [
        "Use one milestone tag per completed phase.",
        "Commit only related files, never git add .",
        "Run npm run build before every commit.",
        "Push tag only after build and commit succeed.",
        "Write rollback notes for any deployment-impacting change.",
      ],
    },
    {
      id: "ai-ops",
      title: "AI Router Operations",
      priority: "high",
      summary:
        "Operational policy for local AI routing and future cloud provider routing.",
      checklist: [
        "Keep Local Runtime Engine as fallback for every AI task.",
        "Record ai.route.executed and ai.route.failed events.",
        "Do not call external AI providers from client components.",
        "Future provider execution must go through server-side API routes.",
        "Validate AI output before writing to project runtime storage.",
      ],
    },
  ];
}

function buildEscalationRules(): string[] {
  return [
    "Critical build failure: stop deployment, fix build, rerun npm run build.",
    "Secret exposure risk: stop commit, remove tracked secret, rotate exposed key if needed.",
    "Broken production route: rollback to last stable deployment or runtime-alpha tag.",
    "Database/RLS issue: disable risky rollout and verify ownership policies before retry.",
    "AI provider failure: fall back to Local Runtime Engine and record ai.route.failed.",
  ];
}

function buildWeeklyReview(): string[] {
  return [
    "Review Activity events for project, AI, deployment, and runtime errors.",
    "Run Tests and Readiness on active projects.",
    "Check Deploy Pack for stale environment or rollback notes.",
    "Review Monitor health score and clear incidents.",
    "Confirm Git tags and Vercel deployments still have a rollback path.",
  ];
}

function buildNextActions(stage: OpsRunbook["operatingStage"]): string[] {
  if (stage === "post_launch") {
    return [
      "Use Monitor and Activity after every release.",
      "Record deployment events for every production change.",
      "Review incidents weekly and keep rollback tags clean.",
    ];
  }

  if (stage === "launch_ready") {
    return [
      "Complete final Tests and Readiness review.",
      "Confirm Deploy Pack and rollback plan.",
      "Record preflight passed before deployment.",
    ];
  }

  return [
    "Do not launch yet.",
    "Complete Code Pack, Tests, Readiness, Deploy, and Monitor checks first.",
    "Resolve critical Ops checklist items before production.",
  ];
}

export function generateOpsRunbook(project: ProjectRuntimeArtifact): OpsRunbook {
  const monitorReport = generateProjectMonitorReport(project);
  const operatingStage = resolveOperatingStage(monitorReport.overallHealthScore);

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    operatingStage,
    sections: buildSections(project),
    escalationRules: buildEscalationRules(),
    weeklyReview: buildWeeklyReview(),
    nextActions: buildNextActions(operatingStage),
    generatedAt: new Date().toISOString(),
  };
}
