type ProjectPageProps = {
  params: Promise<{
    id: string;
  }>;
};

export default async function ProjectPage({ params }: ProjectPageProps) {
  const { id } = await params;

  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <p className="text-sm uppercase tracking-[0.3em] text-cyan-400">
        Project
      </p>

      <h1 className="mt-2 text-4xl font-bold">Project {id}</h1>

      <div className="mt-10 grid gap-6">
        {["Overview", "Brain", "PRD", "Architecture", "Tasks"].map((item) => (
          <section
            key={item}
            className="rounded-2xl border border-white/10 bg-white/5 p-6"
          >
            <h2 className="text-2xl font-semibold">{item}</h2>
            <p className="mt-3 text-slate-400">
              This section will be generated by DevCommander Runtime.
            </p>
          </section>
        ))}
      </div>
    </main>
  );
}