import type {
  AiProviderId,
  AiRouterMode,
  AiRouterPlan,
  AiRouterProvider,
  AiRoutingRule,
  AiTaskType,
} from "@/lib/ai-router/router-types";
import type {
  ProjectRuntimeArtifact,
  RuntimeSection,
} from "@/lib/project/project-runtime";

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: UnknownRecord | undefined, key: string): string | null {
  if (!record) return null;

  const value = record[key];

  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function sectionToText(section: RuntimeSection): string {
  if (section === null || section === undefined) return "";

  if (typeof section === "string") return section;

  if (Array.isArray(section)) {
    return section
      .map((item) => {
        if (typeof item === "string") return item;

        try {
          return JSON.stringify(item, null, 2);
        } catch {
          return "";
        }
      })
      .join("\n");
  }

  try {
    return JSON.stringify(section, null, 2);
  } catch {
    return "";
  }
}

function hasAny(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();

  return keywords.some((keyword) => lower.includes(keyword.toLowerCase()));
}

function getProjectTitle(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const productName =
      readString(project.prd, "productName") ??
      readString(project.prd, "title") ??
      readString(project.prd, "name");

    if (productName) return productName;
  }

  const firstSentence = project.input.split(/[.!?。！？]/)[0]?.trim();

  return firstSentence && firstSentence.length >= 3
    ? firstSentence.slice(0, 80)
    : "Generated Product";
}

function getProjectSummary(project: ProjectRuntimeArtifact): string {
  if (isRecord(project.prd)) {
    const summary =
      readString(project.prd, "summary") ??
      readString(project.prd, "overview") ??
      readString(project.prd, "description");

    if (summary) return summary;
  }

  return project.input.trim() || "Generated by DevCommander OS.";
}

function resolveRouterMode(project: ProjectRuntimeArtifact): AiRouterMode {
  const text = [
    project.input,
    sectionToText(project.prd),
    sectionToText(project.architecture),
    sectionToText(project.tasks),
    sectionToText(project.exportPack),
  ].join("\n");

  const hasEnterpriseSignals = hasAny(text, [
    "enterprise",
    "team",
    "workspace",
    "audit",
    "monitoring",
    "security",
    "scale",
    "permission",
    "role",
  ]);

  const hasCloudSignals = hasAny(text, [
    "deploy",
    "vercel",
    "supabase",
    "database",
    "api",
    "production",
  ]);

  if (hasEnterpriseSignals) return "enterprise";
  if (hasCloudSignals) return "cloud_ready";
  return "local_first";
}

function buildProviders(): AiRouterProvider[] {
  return [
    {
      id: "local",
      name: "Local Runtime Engine",
      status: "available",
      role: "Fallback and deterministic planning engine.",
      strengths: [
        "No API key required",
        "Works in local-first mode",
        "Safe for planning, scoring, and static generation",
      ],
      requiredEnvKeys: [],
      safetyNotes: [
        "Does not call external AI providers.",
        "Best for deterministic rules, readiness checks, and generated starter packs.",
      ],
    },
    {
      id: "openai",
      name: "OpenAI Provider",
      status: "needs_key",
      role: "Primary reasoning and product generation provider.",
      strengths: [
        "Strong PRD generation",
        "Strong architecture reasoning",
        "Strong code explanation and transformation",
      ],
      requiredEnvKeys: ["OPENAI_API_KEY"],
      safetyNotes: [
        "Keep OPENAI_API_KEY server-side only.",
        "Never expose provider keys through NEXT_PUBLIC variables.",
      ],
    },
    {
      id: "anthropic",
      name: "Anthropic Provider",
      status: "needs_key",
      role: "Long-context review and safety-oriented reasoning provider.",
      strengths: [
        "Long-form review",
        "Risk analysis",
        "Policy and requirement consistency checks",
      ],
      requiredEnvKeys: ["ANTHROPIC_API_KEY"],
      safetyNotes: [
        "Keep ANTHROPIC_API_KEY server-side only.",
        "Use as review or fallback provider for large documents.",
      ],
    },
    {
      id: "gemini",
      name: "Gemini Provider",
      status: "needs_key",
      role: "Alternative multimodal and fallback provider.",
      strengths: [
        "Alternative generation path",
        "Fallback routing",
        "Future multimodal product analysis",
      ],
      requiredEnvKeys: ["GEMINI_API_KEY"],
      safetyNotes: [
        "Keep GEMINI_API_KEY server-side only.",
        "Do not commit provider credentials to Git.",
      ],
    },
  ];
}

function buildRule({
  taskType,
  label,
  primaryProvider,
  fallbackProviders,
  reason,
}: {
  taskType: AiTaskType;
  label: string;
  primaryProvider: AiProviderId;
  fallbackProviders: AiProviderId[];
  reason: string;
}): AiRoutingRule {
  return {
    taskType,
    label,
    primaryProvider,
    fallbackProviders,
    reason,
  };
}

function buildRoutingRules(mode: AiRouterMode): AiRoutingRule[] {
  const cloudPrimary: AiProviderId =
    mode === "local_first" ? "local" : "openai";

  return [
    buildRule({
      taskType: "product",
      label: "Product / PRD generation",
      primaryProvider: cloudPrimary,
      fallbackProviders: ["local", "anthropic", "gemini"],
      reason:
        "Product planning needs strong reasoning but must fall back to local deterministic generation when no provider key exists.",
    }),
    buildRule({
      taskType: "architecture",
      label: "Architecture generation",
      primaryProvider: cloudPrimary,
      fallbackProviders: ["local", "anthropic", "gemini"],
      reason:
        "Architecture generation requires system design reasoning, security boundaries, and stack consistency checks.",
    }),
    buildRule({
      taskType: "code",
      label: "Code Pack generation",
      primaryProvider: "local",
      fallbackProviders: ["openai", "anthropic", "gemini"],
      reason:
        "Current Code Pack output is deterministic and secret-safe. Cloud AI can be added later for richer code generation.",
    }),
    buildRule({
      taskType: "deployment",
      label: "Deployment Pack generation",
      primaryProvider: "local",
      fallbackProviders: ["openai", "anthropic"],
      reason:
        "Deployment packs should be deterministic, auditable, and stable before adding external AI suggestions.",
    }),
    buildRule({
      taskType: "monitoring",
      label: "Monitoring and audit review",
      primaryProvider: "local",
      fallbackProviders: ["anthropic", "openai"],
      reason:
        "Audit and readiness checks must remain stable even when cloud AI providers are unavailable.",
    }),
  ];
}

function buildSafetyPolicies(): string[] {
  return [
    "All provider API keys must stay server-side only.",
    "Never use NEXT_PUBLIC_* for private AI provider keys.",
    "Never commit .env, .env.local, service role keys, provider tokens, private keys, or PEM files.",
    "Every AI route must support local fallback.",
    "External AI failures must not break Project Runtime, Code Pack, Deploy Pack, or Readiness Gate.",
    "Provider output must be validated before being written to project runtime storage.",
  ];
}

function buildNextActions(mode: AiRouterMode): string[] {
  if (mode === "local_first") {
    return [
      "Keep Local Runtime Engine as the default provider.",
      "Add server-only provider key support later through API routes.",
      "Do not expose AI provider keys in browser code.",
      "Use AI Router rules to decide which engine handles PRD, architecture, code, deploy, and monitoring tasks.",
    ];
  }

  if (mode === "cloud_ready") {
    return [
      "Create server-side API route for provider execution.",
      "Add provider key validation without exposing secrets.",
      "Keep local fallback enabled for every task type.",
      "Add audit events for ai.route.selected and ai.route.failed.",
    ];
  }

  return [
    "Add role-based access control before enabling team AI routing.",
    "Create server-side provider execution logs.",
    "Add per-workspace provider policy configuration.",
    "Add cost and rate-limit tracking before production AI routing.",
  ];
}

export function generateAiRouterPlan(
  project: ProjectRuntimeArtifact,
): AiRouterPlan {
  const mode = resolveRouterMode(project);

  return {
    projectId: project.projectId,
    title: getProjectTitle(project),
    summary: getProjectSummary(project),
    mode,
    providers: buildProviders(),
    rules: buildRoutingRules(mode),
    safetyPolicies: buildSafetyPolicies(),
    nextActions: buildNextActions(mode),
    generatedAt: new Date().toISOString(),
  };
}